package com.example.project_3;

import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.*;

import java.io.*;
import java.net.URL;
import java.util.ArrayList;
import java.util.Objects;
import java.util.ResourceBundle;

public class FavoriteMoviesController implements Initializable{

    @FXML
    public Button addMovieButton;
    public Label titleText;

    @FXML
    private TextField movieNameField;

    @FXML
    private ChoiceBox<String> genreBox;

    @FXML
    private CheckBox actionCheckbox;

    @FXML
    private CheckBox thrillerCheckbox;

    @FXML
    private CheckBox romanceCheckbox;

    @FXML
    private CheckBox comedyCheckbox;

    @FXML
    private CheckBox fantasyCheckbox;

    @FXML
    private ListView<String> moviesListView;

    @FXML
    private ListView<String> tempMovieListView;

    @FXML
    private Button saveMoviesListButton;

    @FXML
    private Button loadMoviesListButton;

    @FXML
    private Button deleteMovie;

    private final ArrayList<Movie> tempMovieArrayList = new ArrayList<>();
    private final ArrayList<Movie> permMovieArrayList = new ArrayList<>();

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        genreBox.getItems().addAll("romance", "thriller", "comedy", "action", "fantasy/sci-fi");
        tempMovieListView.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);
    }

    @FXML
    protected void onAddMovieButtonClick() {
        String movieName = movieNameField.getText();
        String movieGenre = genreBox.getSelectionModel().getSelectedItem();
        Movie movie = new Movie(movieName, movieGenre);

        tempMovieArrayList.add(movie);
        updateTempMovieViewList(tempMovieArrayList);

        movieNameField.clear();
    }

    @FXML
    protected void onSaveMoviesListButtonClick(){
        // create file
        File file = new File("movies.txt");

        // write to file
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))){
            for (Movie movie : tempMovieArrayList){
                writer.write(movie.toString());
                writer.newLine();
            }
            writer.close();
            System.out.println("Successfully wrote to the file.");
        } catch (IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }

        tempMovieListView.getItems().clear();
    }

    @FXML
    protected void onDeleteMovieButtonClick() {
        ObservableList<String> items = tempMovieListView.getSelectionModel().getSelectedItems();
        for (String item : items) {
            String[] parts = item.split(",");
            String name = parts[0];

            // syntax recommended by the ide
            // remove movie from list if the names match
            tempMovieArrayList.removeIf(movie -> Objects.equals(name, movie.getName()));
        }
        updateTempMovieViewList(tempMovieArrayList);
    }

    @FXML
    protected void onLoadMoviesListButtonClick(){
        String filePath = "movies.txt";
        if (isFileEmpty(filePath)){
            Alert alert = new Alert(Alert.AlertType.INFORMATION);
            alert.setContentText("The file is empty, please add movies before loading!");
            alert.showAndWait();
        }
        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                String name = parts[0];
                String genre = parts[1];
                Movie movie = new Movie(name, genre);
                permMovieArrayList.add(movie);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        updatePermMovieViewList(permMovieArrayList);
    }

    protected void updateTempMovieViewList(ArrayList<Movie> arrayList){
        tempMovieListView.getItems().clear();
        for (Movie movie : arrayList){
            if (!tempMovieListView.getItems().contains(movie + "\n")){
                tempMovieListView.getItems().add(movie + "\n");
            }
        }
    }

    protected void updatePermMovieViewList(ArrayList<Movie> arrayList){
        moviesListView.getItems().clear();
        for (Movie movie : arrayList){
            if (!moviesListView.getItems().contains(movie + "\n")){
                moviesListView.getItems().add(movie + "\n");
            }
        }
    }

    // generated by google search
    protected boolean isFileEmpty(String filepath){
        File file = new File(filepath);
        return file.length() == 0;
    }
}